# Generated by Django 4.2.15 on 2024-08-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_remove_service_admin_action'),
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaction',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sellers.service'),
        ),
    ]
