# Generated by Django 4.2.15 on 2024-08-14 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='admin_action',
        ),
    ]
