# Generated by Django 4.2.23 on 2025-08-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_service_admin_comments_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='availability',
            field=models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=15),
        ),
    ]
