# Generated by Django 4.2.23 on 2025-08-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('not available', 'Not Available')], default='Available', max_length=15),
        ),
    ]
