# Generated by Django 4.2.15 on 2024-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_payment_stripe_charge_id_payment_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('Card', 'Card')], default='Cash', max_length=20),
        ),
    ]
