# Generated by Django 4.2.15 on 2024-08-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_payment_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('acceped', 'Accepted'), ('declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
