# Generated by Django 4.2.15 on 2024-08-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='progress',
            field=models.CharField(choices=[('completed', 'Completed'), ('on-going', 'On-going'), ('pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
