# Generated by Django 4.2.15 on 2024-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_booking_date_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('acceped', 'Accepted'), ('declined', 'Declined')], default='Pending', max_length=20),
        ),
    ]
